spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: smpas
    password: 1703
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  opening: "10:00"
  closing: "20:00"
  intervalMinutes: 20
  linkExpirationTimeMinutes: 15
  host: "localhost"
  port: 8080